export const items = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/iphone14.jpg?updatedAt=1718166388383",
    amazonLink: "https://amzn.eu/d/bMF8463",
    description: [
      "15.40 cm (6.1-inch) Super Retina XDR display",
      "Advanced camera system for better photos in any light",
      "Cinematic mode now in 4K Dolby Vision up to 30 fps",
      "Action mode for smooth, steady, handheld videos",
      "Vital safety technology — Crash Detection calls for help when you can’t",
      "All-day battery life and up to 20 hours of video playback",
      "Industry-leading durability features with Ceramic Shield and water resistance",
      "A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular",
      "iOS 16 offers even more ways to personalise, communicate and share",
    ],
    price: "89999",
  },
  {
    id: 2,
    category: "laptops",
    title: "ASUS [SmartChoice] Vivobook 16X",
    imgSrc:
      "https://ik.imagekit.io/8euik0bwt/Ecart/asusVivobook16x.webp?updatedAt=1718166388196",
    amazonLink: "https://amzn.eu/d/fHF0HFx",
    description: [
      "Processor: AMD Ryzen 5 5600H Mobile Processor (6-core/12-thread, 19MB cache, up to 4.2 GHz max boost)",
      "Memory: 8GB DDR4 onboard with | Storage: 512GB M.2 NVMe PCIe 3.0 SSD",
      "Display: 16:10 aspect ratio LED Backlit 300nits, IPS-level Panel, Anti-glare display, 86 % Screen-to-body ratio",
      "Graphics: Integrated AMD Radeon Vega 7 Graphics",
      "Operating System: Windows 11 Home | Software: Office Home and Student 2021 included",
      "Design: 1.99 ~ 1.99 cm Thin | Thin & Light | 1.80 kg weight",
      "Battery: 50WHrs Battery Capacity | Up to 8 hours Battery life, Note: Battery life depends on conditions of usage",
      "Keyboard: Backlit Chiclet Keyboard with Num-key | 1.4mm key travel",
      "I/O Port: 1x USB 2.0 Type-A, 1x USB 3.2 Gen 1 Type-C, 2x USB 3.2 Gen 1 Type-A, 1x micro HDMI 1.4, 1x 3.5mm Combo Audio Jack",
      "Other: 720p HD camera With privacy shutter | Wi-Fi 6(802.11ax) (Dual band) 2*2 + Bluetooth 5.2 | FingerPrint Reader | Built-in speaker | Built-in array microphone",
    ],
    price: "49999",
  },
  {
    id: 3,
    category: "tablets",
    title: "Samsung Galaxy Tab S9 FE",
    imgSrc:
      "https://ik.imagekit.io/8euik0bwt/Ecart/samsungS9.jpg?updatedAt=1718166388393",
    amazonLink: "https://amzn.eu/d/jdOMWNL",
    description: [
      "Outstanding vividness with 27.69 cm (10.9”) display, 90 Hz Refresh Rate, 2304 x 1440 (WQXGA, 249 PPI)",
      "Powerful Performance with Exynos 1380 chip",
      "8 MP Rear Camera,  12 MP Ultra wide Front camera, Dual Speakers by AKG",
      "8000 mAh Battery, Dual Sim pSIM + eSIM",
      "Weatherproof & DurableTablet and S Pen with IP68",
    ],
    price: "47999",
  },
  {
    id: 4,
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/iphone11.jpg?updatedAt=1718166388378",
    amazonLink: "https://amzn.eu/d/bcaUviu",
    description: [
      "6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
      "Water and dust resistant (2 meters for up to 30 minutes, IP68)",
      "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
      "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo",
      "Face ID for secure authentication",
      "A13 Bionic chip with third-generation Neural Engine",
      "Fast-charge capable",
    ],
    price: "69999",
  },
  {
    id: 5,
    category: "tablets",
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/lonovoTab.jpg?updatedAt=1718166388410",
    amazonLink: "https://amzn.to/3RabsdH",
    description: [
      "12.6 inch (2560 X 1600) AMOLED display| 600 nits brightness | Dolby Vision| HRD10+| TUV Certified Full care display|",
      "5.63 mm thin | 565 gm light | 89% screen-to-display ratio",
      "Qualcomm Snapdragon 870 octa core processor with Adreno 650 GPU and 3.2 GHz clock speed |8GB RAM| 256 GB ROM| Expandable upto 512 GB",
      "Android 11 OS| 10200 mAH battery |5MP Wide + 13MP Auto-Focus rear camera| 8MP Fixed-Focus + TOF Sensor front camera| Google Kids Space",
      "Lenovo Premium Audio Design and Tuning| Dolby Atmos|Entertainment Space| ",
      "Precision Pen 3| 4096 tilt and pressure sensitivity to write| Attaches magnetically for charging| Click to action| ",
      "Anti-lost alert| Remote control",
    ],
    price: "19999",
  },
  {
    id: 6,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/iphone13.jpg?updatedAt=1718166388425",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: [
      "15 cm (6.1-inch) Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    price: "79999",
  },
  {
    id: 7,
    category: "laptops",
    title: "Lenovo IdeaPad Slim 5 ",
    imgSrc:
      "https://ik.imagekit.io/8euik0bwt/Ecart/lenovoIdeapadSlim5.jpg?updatedAt=1718166388394",
    amazonLink: "https://amzn.to/44JsK4r",
    description: [
      "HD Audio",
      "Memory Card Slot",
      "Anti Glare Coating",
      "Backlit Keyboard",
    ],
    price: "29999",
  },
  {
    id: 8,
    category: "tablets",
    title: "Samsung Galaxy Tab A9+",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/galaxyTabA9plus.jpg?updatedAt=1718166388399",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description: [
      "26.69cm (10.5 inch) Vibrant Display 1920x1200 (WUXGA) TFT,” Aspect ratio 16:10. Symmetric Narrow Bezel",
      "Android 11.0, Quad speakers with Dolby Atmos Speakers .",
      "8MP AF + 5.0MP Camera, 7040 mAh Battery With 15W Fast Charging",
      "3 GB RAM, 32 GB Internal Memory (expandable to 1 TB); UniSOC T618 (Dual 2.0GHz + Hexa 2.0GHz)",
      "Display Type: Lcd; Processor Description: Octa-Coreunisoc T618dual 2.0ghz + Hexa 2.0ghz; Hardware Interface: Bluetooth 5; Graphics Description: Integrated; Wireless Communication Technology: Cellular; Cellular Technology: 4g",
    ],
    price: "49999",
  },
  {
    id: 9,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://ik.imagekit.io/8euik0bwt/Ecart/mackbookAir.jpg?updatedAt=1718166388168",
    amazonLink: "https://amzn.to/3r9rvhm",
    description: [
      "All-Day Battery Life – Go longer than ever with up to 18 hours of battery life.",
      "Powerful Performance – Take on everything from professional-quality editing to action-packed gaming with ease. The Apple M1 chip with an 8-core CPU delivers up to 3.5x faster performance than the previous generation while using way less power.",
      "Superfast Memory – 8GB of unified memory makes your entire system speedy and responsive. That way it can support tasks like memory-hogging multitab browsing and opening a huge graphic file quickly and easily.",
      "Stunning Display – With a 13.3-inch/33.74 cm Retina display, images come alive with new levels of realism. Text is sharp and clear, and colors are more vibrant.",
      "Why Mac – Easy to learn. Easy to set up. Astoundingly powerful. Intuitive. Packed with apps to use right out of the box. Mac is designed to let you work, play, and create like never before.",
    ],
    price: "129999",
  },
];
